- src/components/diaryProductsList/diaryProductsList.js
- src/components/diaryProductsList/index.js
- src/components/diaryProductsListItem/diaryProductsListItem.js
- src/components/diaryProductsListItem/index.js
- src/index.css
- src/pages/diaryPage/diaryPage.js
Добавив компоненти  diary products list/item
> Features/diary products list/item

- src/components/diaryProductsList/diaryProductsList.js
- src/components/diaryProductsListItem/diaryProductsListItem.js
- src/redux/day/day_action.js
- src/redux/day/day_operation.js
- src/redux/day/day_reducer.js
Добавив логіку відображення списка зїджених продуктів+видалення+токен в хедерс при запросах
> Feature/diary products list/all products/delete products

- src/App.js
> updated redirection routes

- src/App.js
> added calculator page

- src/pages/calculatorPage/calculatorPage.js
added mobmenu on calculator page
> added mobMenu in calculator page

- src/App.js
- src/components/appBar/appBar.js
- src/components/burger/burger.js
- src/components/burger/index.js
- src/components/navigation/navigation.js
- src/components/userInfo/userInfo.js
> styles in header a bit changed

- src/components/logo/logo.js
- src/components/navigation/navigation.js
chenged logo for loggedin user mobile version
> updated logo for loggedin user mobile

- src/components/appBar/appBar.js
- src/components/appBar/appBar.module.css
- src/components/burger/burger.js
- src/components/logo/logo.js
- src/components/navigation/navigation.js
- src/components/userInfo/userInfo.js
> header styles completed

- src/components/diaryProductsList/diaryProductsList.js
- src/components/diaryProductsListItem/diaryProductsListItem.js
- src/helpers/currentDateLocal.js
Поправив видалення продуктів
коли пустий список відображається напис що нічого не їлось
> Bugfix/diary products list/delete products

- src/redux/auth/authSlice.js
fixed double user in redux while fetching currentuser
> fixed double user in redux after fetching currentuser

- src/components/navigation/navigation.js
> fixed navigation menu currentColor

- src/components/appBar/appBar.module.css
- src/pages/calculatorPage/calculatorPage.js
> sidebar fixed

- src/components/appBar/appBar.js
- src/components/navigation/navigation.js
- src/components/userInfo/userInfo.js
- src/helpers/mobileMenuContext/mobileMenuContext.js
- src/pages/diaryPage/diaryPage.js
- src/pages/diaryPage/diaryPage.module.css
- src/redux/auth/authOperations.js
- src/redux/auth/authSlice.js
> added arrow and added redux token while register

- src/components/appBar/appBar.js
- src/components/mainPage/mainPage.js
- src/pages/calculatorPage/calculatorPage.js
- src/pages/diaryPage/diaryPage.js
- src/pages/homePage/homePage.js
> arrows working

- src/pages/calculatorPage/calculatorPage.js
- src/pages/diaryPage/diaryPage.js
- src/pages/homePage/homePage.js
> mobmenu fixed

- src/pages/calculatorPage/calculatorPage.js
- src/pages/diaryPage/diaryPage.js
fixed green container width with an arrow
> fixed green container

- src/components/authNav/authNav.js
- src/index.js
- src/pages/homePage/homePage.js
> fixed authmenu color

- src/components/rightSideBar/rightSideBar.js
> fix rightSideBar

- src/components/dailyCaloriesForm/dailyCaloriesForm.js
> scroll fixed

- src/components/dailyCaloriesForm/dailyCaloriesForm.js
> scroll done
